language: python

python:
  - 2.7

before_install:
  - sudo apt-get install python-qt4 python-sip-dev
  - pip install twisted pyopenssl qt4reactor

install:
  - scons -C rdpy/core install

script:
  - python -m unittest discover -s test

